version: 1
module_version: 0.2.0

test_defaults:
  runner_image: "312851193143.dkr.ecr.us-west-2.amazonaws.com/infrastructure"

  before_init:
    - spacelift-configure-paths
    - spacelift-git-use-https
